FROM golang:1.21-bullseye
WORKDIR /migrations

# Copy migration files
COPY db/migrations /migrations

# Copy the wait-for-it script
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Install migrate tool
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

CMD /wait-for-it.sh postgresdb:5432 -- sh -c 'migrate -path=/migrations -database ${DATABASE_URL} up'