version: "3.8"
services:
  pg-db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      DB_URL: ${DB_URL}
    depends_on:
      pg-db:
        condition: service_healthy
    restart: on-failure

  web-app:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - 4000:4000
    environment:
      DB_URL: ${DB_URL}
    depends_on:
      - migrations
    command: ["./main"]

volumes:
  postgres_data: