version: "3.8"
services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:${PGADMIN_PORT}"
    depends_on:
      - postgres

volumes:
  pgdata: