version: "3.8"
services:
  postgresdb:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
  migrations:
      build:
        context: .
        dockerfile: Dockerfile.migrations
      environment:
        DATABASE_URL: ${DATABASE_URL}
      depends_on:
        - postgresdb
  webapp:
      build: .
      ports:
        - "4000:4000"
      environment:
        DATABASE_URL: ${DATABASE_URL}
      depends_on:
        - migrations
      command: ["/wait-for-it.sh", "postgresdb:5432", "--", "./main"]